groups:
  - name: node_exporter_recording
    rules:
      - record: instance:node_cpu_usage:avg
        expr: avg(rate(node_cpu_seconds_total{mode!='idle'}[5m])) by (instance)
      - record: instance:node_memory_usage_bytes:avg
        expr: avg(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)
      - record: instance:node_memory_usage_percent:avg
        expr: avg((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100) by (instance)
      - record: instance:node_disk_io:avg
        expr: avg(rate(node_disk_io_time_seconds_total[5m])) by (instance)
      - record: instance:node_network_io:avg
        expr: avg(rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m])) by (instance)
  
  - name: windows_exporter_recording
    rules:
      - record: instance:windows_cpu_usage:avg
        expr: (1 - avg by (instance)(rate(windows_cpu_time_total{mode="idle"}[5m]))) * 100
      - record: instance:windows_memory_usage_percent:avg
        expr: avg(windows_memory_committed_bytes / windows_memory_commit_limit * 100) by (instance)
      - record: instance:windows_disk_io:avg
        expr: avg(rate(windows_logical_disk_io_time_total[5m])) by (instance)
      - record: instance:windows_network_io:avg
        expr: avg(rate(windows_network_interface_bytes_total[5m])) by (instance)

  - name: dcgm_exporter_recording
    rules:
      - record: instance_gpu:dcgm_gpu_utilization:avg
        expr: avg(dcgm_gpu_utilization) by (instance)
      - record: instance_gpu:dcgm_memory_usage_bytes:avg
        expr: avg(dcgm_fb_used) by (instance)
      - record: instance_gpu:dcgm_memory_usage_percent:avg
        expr: avg(dcgm_fb_used / dcgm_fb_total * 100) by (instance)

  - name: application_recording
    rules:
      - record: instance_endpoint:http_requests_latency_seconds:p95_5m
        expr: histogram_quantile(0.95, sum(rate(http_requests_latency_seconds_bucket[5m])) by (le, instance, endpoint))

      - record: endpoint:http_requests_total:max
        expr: max(http_requests_total) by (endpoint)

      - record: instance_endpoint_status:http_requests:error_rate_5m
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m])) by (instance, endpoint, status)
          /
          sum(rate(http_requests_total[5m])) by (instance, endpoint, status)
